name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet build src/AutoGrating/TeklaAutoGrating.csproj -c Release
      - uses: actions/upload-artifact@v4
        with:
          name: TeklaAutoGrating
          path: src/AutoGrating/bin/Release/net48/TeklaAutoGrating.dll
